[package]
name = "objsds-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[features]
rustfs-e2e = []

[[test]]
name = "rustfs"
required-features = ["rustfs-e2e"]

[[test]]
name = "rustfs_perf"
required-features = ["rustfs-e2e"]

[dependencies]
objsds.workspace = true
objsds-queue.workspace = true
objsds-store.workspace = true
objsds-store-memory.workspace = true
objsds-store-filesystem.workspace = true
objsds-store-s3.workspace = true
s3-client.workspace = true
serde.workspace = true
tempfile.workspace = true
